cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    # Utilize seu próprio bucket
    bucket-name: ${BUCKET_NAME}

spring:
  application:
    name: gerenciadortarefas
  security:
    user:
      name: user
      password: 123
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: gerenciador-tarefas
    redis:
      host: redis
      port: 6379

server:
  port: 8089

logging:
  level:
    root: debug