cloud:
  aws:
    credentials:
      access-key: AKIAYS2NWB56SXWDXH6N
      secret-key: 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

spring:
  application:
    name: gerenciadortarefas
  security:
    user:
      name: user
      password: 123
  data:
    mongodb:
      host: mongodb
      port: 27017
    redis:
      host: redis
      port: 6379

server:
  port: 8089

logging:
  level:
    root: debug