spring:
  application:
    name: gerenciadortarefas
  security:
    user:
      name: user
      password: 123
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8089

logging:
  level:
    root: debug