spring:
  application:
    name: gerenciadortarefas
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8089

logging:
  level:
    root: debug